storyscript/runtime

asyncy/processing/Lexicon.py, tests/unit/processing/Lexicon.py
Inline expressions are compiled with line['name'] instead of line['output'].
=> Add support for line['name'] within the tree.

asyncy/Containers.py, tests/unit/Containers.py
This is an experiment.
This is because apparently Kubernetes has trouble resolving DNS of a
pod that has been created, destroyed, and then created again with the
same name.
=> Use app version as a part of the container name.

asyncy/processing/Lexicon.py, setup.py, tests/integration/processing/Lexicon.py, tests/unit/processing/Lexicon.py
Why? Because Storyscript's line["exit"] doesn't work properly.
=> Use our technique of determining the next line after a foreach.

asyncy/processing/Story.py, tests/unit/processing/Story.py
If we copy the output from all blocks, then foreach is affected.
=> Copy output from when blocks only.

asyncy/Kubernetes.py, tests/unit/Kubernetes.py
Why? Because k8s doesn't like / in the value of a label.
=> Encode the service name as base 16.

asyncy/Apps.py, asyncy/enums/ReleaseState.py, tests/unit/Apps.py
Closes #290 
- Apps are now deployed in parallel during a restart
- All app deployments time out after 5 minutes
=> Deploy apps in parallel

asyncy/utils/TypeResolver.py, tests/integration/processing/Lexicon.py
If a value is None, and you cast it to a string, it returns `'None'` - the string value, and not the actual None type.
=> Cast null to null, instead of "None".

tests/integration/processing/Lexicon.py
Counter-part of https://github.com/storyscript/storyscript/pull/905 for the engine.
tl;dr: the engine currently doesn't support globals. Thus, the Storyscript compiler will error. However, as we want to implement this feature soon (and it makes the test suites so much nicer), Storyscript already comes with a `-preview=globals` switch. It can be activated via the API as shown below.
This will be required for SS 0.20.
=> Set -preview=globals for all integration tests

asyncy/http_handlers/StoryEventHandler.py, tests/unit/http_handlers/StoryEventHandler.py
This is a hack, since JSON cannot carry this type of information.
Closes #319.
=> Make HTTP headers case insensitive.

asyncy/processing/Services.py, tests/unit/processing/Services.py
This fixes the issue we discussed previously.
e.g.
```
runtime: An exception has occurred:
Failed to execute line: 'NoneType' object has no attribute 'get'
at line 2: when client listen path: "/status" as request (in src/health.story)
at line 4: redis get key: "__health_key_non_existent_ok" (in src/health.story)
```
=> Fix for ServiceOutputValidator

setup.py, tests/integration/processing/Lexicon.py
These are the changes which will be required for the upcoming 0.21 release of Storyscript.
As usual this hasn't been released yet, so the CI will fail.
Also, no engines changes are required, only a few lines in the test suite are no longer valid, because implicit casting to `boolean` is no longer supported.
=> Upgrade to Storyscript 0.21

asyncy/Apps.py, tests/unit/Apps.py
Disabling since there's an unhandled case for k8s, when the pod label value becomes longer than 63 characters.
=> Disable service usage recording temporarily

asyncy/processing/mutations/FloatMutations.py, asyncy/processing/mutations/IntegerMutations.py, setup.py, tests/integration/processing/Lexicon.py
- With 0.22 the old mutation syntax isn't supported anymore
- Testcases for chained dot mutation (will require 0.22 with fixes)
=> Upgrade for Storyscript 0.22: remove old mutation syntax

storyruntime/processing/Lexicon.py, tests/integration/processing/Lexicon.py
This will make sure cases like the following work fine:
```
a = ["foo", "bar"]
foreach a as s
try
if s == "bar"
continue
when twitter stream tweet track: s as result
log info msg: result['text']
finally
log info msg: "wow"
```
Right now sentinels from within try catch aren't bubbled up.
We should be doing that.
Fixes: #511
=> feat(Lexicon): handle sentinels from executing try catch finally

setup.py
The motivation for this is to enable users to simply clone the project, and then be able to run python setup.py test. Will and I explored another option of forcing users to run tox instead of the setuptools test, but were unable to successfully override the test command and print a decent message. Hence, for now, we'll just pin the same versions (since they rarely change anyway).
=> Pin versions of the test deps to that mentioned in the tox.ini.

storyruntime/utils/Resolver.py, tests/integration/processing/Lexicon.py
Closes #270
Docs list the following types, of which the ones highlighted in bold can be added at the moment:
- comments
- boolean
- **numbers (int, float)**
- **strings**
- **lists**
- maps
- **time**
- regex
=> Allow list + list

setup.py, storyruntime/processing/Lexicon.py, tests/integration/processing/Lexicon.py, tests/unit/processing/Lexicon.py
TODO:
```
Case(append='a = {2: "42"} as Map[float,float]',
assertion=ContextAssertion(key='a', expected={2.: 42.})),
```
=> Storyscript 0.25

requirements.txt, setup.py, storyruntime/processing/Lexicon.py, tests/unit/processing/Lexicon.py
This is a change with the compiler, starting from 0.25.0.
Closes #646
=> Lexicon#execute should look at "enter", and not "next".

storyruntime/ServiceUsage.py
Related to https://github.com/storyscript/runtime/issues/573
I can't seem to figure out why any pod would have no containers, so this will help us see that pod's name when such a situation occurs
=> Raise exception for service metrics error

storyruntime/ServiceUsage.py, tests/unit/ServiceUsage.py
Closes #573
For containers that have not started yet, k8s reports no metrics for their pods - and this check is accounted for already..
but it looks like if a container crashes, the API still returns metrics for it, except they're just empty
=> Don't attempt to scrape metrics for crashed containers

setup.cfg
Fixes #687 
> For Codecov to operate properly, all files in the coverage report must match the git/hg file structure.
=> Update pytest-cov config

storyruntime/Apps.py, storyruntime/db/Database.py, tests/unit/Apps.py, tests/unit/db/Database.py
Fixes #671 
Reproduced as:
- Run `story apps delete`. This sets `app.deleted = True` and sends a notification to the runtime which sets the latest release's state to `NO_DEPLOY`.
- When the runtime restarts, it still recieves the app's UUID from `Database.get_all_app_uuids_for_deployment` since that doesn't check for `app.deleted` or `NO_DEPLOY`.
- This UUID is passed on to `Database.get_release_for_deployment` which tries to find the release to deploy for the app. This function discards releases that have `state` set to `NO_DEPLOY`, so it's unable to find an appropriate release, causing the error.
The following weird behavior still remains though:
- If you delete an app that has 10 releases, the delete action will only set the latest release to `NO_DEPLOY`. The runtime will attempt to …
=> Don't try to deploy deleted apps
