storyscript/runtime

asyncy/Metrics.py
asyncy/Service.py
asyncy/Stories.py
asyncy/processing/Lexicon.py
asyncy/processing/Story.py
asyncy/processing/internal/HttpEndpoint.py
setup.py
tests/unit/Stories.py
tests/unit/processing/Story.py

chore(stories): Expose basic metrics around stories.

---

asyncy/processing/Lexicon.py
tests/unit/processing/Lexicon.py

fix(stories): Fix foreach to use the new output field.

---

asyncy/App.py
asyncy/Stories.py
tests/conftest.py
tests/integration/Containers.py
tests/integration/examples/stories.json
tests/unit/App.py
tests/unit/Containers.py
tests/unit/Stories.py
tests/unit/processing/Story.py

Read entrypoint from stories.json, and from each story.

---

asyncy/processing/internal/HttpEndpoint.py
tests/unit/processing/internal/HttpEndpoint.py

Add http-endpoint/flush.

---

asyncy/App.py
asyncy/Containers.py
asyncy/Stories.py
asyncy/processing/Story.py
tests/conftest.py
tests/integration/Containers.py
tests/unit/Containers.py
tests/unit/processing/Story.py
tests/unit/processing/conftest.py

Match container lifecycle to that of asyncy/platform-bootstrap.

---

asyncy/Containers.py
asyncy/Exceptions.py
tests/unit/Containers.py

Enforce required environment variables for services.

---

asyncy/Stories.py
tests/unit/Stories.py

Print truncated variable values in the debug log.

---

asyncy/processing/Story.py
asyncy/utils/Resolver.py
setup.py
tests/unit/utils/Resolver.py

Support for new style expressions.

---

asyncy/App.py
asyncy/Apps.py
asyncy/Exceptions.py
asyncy/Kubernetes.py
setup.py
tests/unit/App.py
tests/unit/Apps.py
tests/unit/Exceptions.py
tests/unit/Kubernetes.py

Add CPU, memory, services, volumes limitations.

---

asyncy/Exceptions.py
asyncy/processing/Services.py
tests/unit/processing/Services.py

Add smart stringify - JSON stringify dict and list like objects.
Closes #130 and #174.

Add strict type checking.

---

asyncy/utils/Resolver.py
setup.py
tests/unit/utils/Resolver.py

Support for not.

---

asyncy/Containers.py
asyncy/Exceptions.py
tests/unit/Containers.py

Handle action not being found in the OMG.

---

asyncy/processing/mutations/StringMutations.py
tests/integration/processing/Lexicon.py

Add string contains.

---

asyncy/utils/Resolver.py
setup.py
tests/integration/processing/Lexicon.py
tox.ini

Support flattened "sum" operations.

---

asyncy/utils/Resolver.py
setup.py
tests/integration/processing/Assertions.py
tests/integration/processing/Lexicon.py
tests/unit/utils/Resolver.py

Upgrade Storyscript to 0.14.3

---

asyncy/Stories.py
asyncy/processing/mutations/DictMutations.py
asyncy/processing/mutations/StringMutations.py
setup.py
tests/integration/processing/Lexicon.py
tests/unit/Stories.py

https://github.com/storyscript/storyscript/releases/tag/0.16.2 (unicode escaping)
https://github.com/storyscript/storyscript/releases/tag/0.17.0 (typing for mutations)
https://github.com/storyscript/storyscript/releases/tag/0.17.1 (newline escaping fix)
https://github.com/storyscript/storyscript/releases/tag/0.17.2 (regexp fix)
https://github.com/storyscript/storyscript/releases/tag/0.17.3 (header typing updates
TODOs:

Upgrade to Storyscript 0.17.3

---

asyncy/Exceptions.py
asyncy/processing/Story.py
asyncy/processing/mutations/ListMutations.py
asyncy/processing/mutations/StringMutations.py
asyncy/utils/Resolver.py
asyncy/utils/TypeResolver.py
setup.py
tests/integration/Containers.py
tests/integration/processing/Assertions.py
tests/integration/processing/Lexicon.py

Will obviously fail because it's not released yet.
Just to show the upcoming changes. Passes locally.
Release notes: https://github.com/storyscript/storyscript/releases/tag/untagged-6c145c68e807c50420ad (draft)

Update the platform engine to Storyscript 0.18.1

---

asyncy/utils/Resolver.py
tests/integration/processing/Lexicon.py

Lexicon: Add support for subtraction

---

asyncy/utils/Resolver.py
tests/integration/processing/Lexicon.py

Lexicon: Add support for exponential

---

asyncy/utils/Dict.py
tests/integration/processing/Lexicon.py

Update map assignment

---

setup.py
tests/integration/processing/Lexicon.py

This release upgrade is pretty short as
- dot mutations lower to the normal mutation json
- read-only variables are a frontend semantic feature
- implicit casts are only an optional hint (and casting is already implemented)
- more frontend bug fixes
I still updated one Lexicon test to the dot mutation syntax to be sure.
See also: https://github.com/storyscript/storyscript/releases/tag/0.19.0

Update the platform engine to Storyscript 0.19.0

---

asyncy/utils/Resolver.py
setup.py
tests/integration/processing/Lexicon.py

Combines https://github.com/storyscript/platform-engine/pull/308, https://github.com/storyscript/platform-engine/pull/307 and https://github.com/storyscript/platform-engine/pull/305

Storyscript 0.20 upgrade

---

setup.py

https://github.com/storyscript/storyscript/releases/tag/0.20.1

Bump to Storyscript 0.20.1

---

asyncy/Kubernetes.py
tests/unit/Kubernetes.py

Check for image pull errors during deployment

---

asyncy/Kubernetes.py
tests/unit/Kubernetes.py

Don't take app argument (app agnostic k8s calls to follow in service metrics)

Update Kubernetes.make_k8s_call signature

---

asyncy/App.py
asyncy/Apps.py
asyncy/db/Database.py
asyncy/entities/Release.py
tests/unit/App.py
tests/unit/Apps.py
tests/unit/Database.py

This is required for the latest exception reporting updates. 
I've also merged https://github.com/storyscript/platform-engine/tree/err_rebrand into this branch to make things easier. Ideally, we should get pr #362 merged into master first.

Adding App Name, and Owner Email To Release/App Info

---

setup.py

See also: https://github.com/storyscript/cli/pull/235

Upgrade to Storyscript 0.21.1

---

.circleci/config.yml
Dockerfile
setup.py
tox.ini

Foundation for #374 (uses asynccontextmanager).

Upgrade to use Python 3.7.

---

setup.py

See also: https://github.com/storyscript/storyscript/releases/tag/0.23.0

Upgrade Storyscript to 0.23.0

---

storyruntime/Exceptions.py
storyruntime/Story.py
tests/integration/processing/Lexicon.py
tests/unit/Story.py

Limit stack frame size.

---

setup.py

Details: https://github.com/storyscript/storyscript/releases/tag/0.23.7

Upgrade Storyscript to 0.23.7

---

storyruntime/processing/Services.py
tests/unit/processing/Services.py

Add support for absolute URLs.

---

storyruntime/processing/Services.py
tests/unit/processing/Services.py

Add support for sending parameters in headers.

---

setup.py

Details: https://github.com/storyscript/storyscript/releases/tag/0.23.8

Upgrade Storyscript to 0.23.8

---

storyruntime/App.py
storyruntime/AppConfig.py
storyruntime/Apps.py
storyruntime/Containers.py
storyruntime/Kubernetes.py
storyruntime/processing/mutations/MapMutations.py
tests/integration/processing/Lexicon.py
tests/unit/App.py
tests/unit/AppConfig.py
tests/unit/Containers.py
tests/unit/Kubernetes.py

Add support for forwards (alias to expose).

---

storyruntime/constants/ServiceConstants.py
storyruntime/processing/Services.py
tests/unit/processing/Services.py

Add support for externally hosted services.

---

storyruntime/processing/Services.py
storyruntime/processing/internal/File.py
tests/integration/processing/Lexicon.py
tests/unit/processing/internal/File.py

This currently adds support for file list, isdir, isfile, and remove. Any recommendations are welcome

File service enhancements

---

setup.py
storyruntime/processing/mutations/ListMutations.py
storyruntime/processing/mutations/MapMutations.py
tests/integration/Containers.py
tests/integration/processing/Lexicon.py

At least this change will be required once 0.24 is released.
See also: https://github.com/storyscript/storyscript/pull/1143

Storyscript 0.24 updates

---

storyruntime/processing/Lexicon.py
tests/integration/processing/Lexicon.py
tests/unit/processing/Lexicon.py

This PR has changes which will be needed to support the storyscript language release which introduces:
* Drop support for whitespace mutation syntax
* Changes in how next attribute in the JSON protocol is populated.
Linked to issues: storyscript/storyscript#1158, storyscript/storyscript#625
Linked to PR: storyscript/storyscript#1173, storyscript/storyscript#1184

Changes for runtime when storyscript is upgraded to next release

---

storyruntime/processing/Lexicon.py
tests/unit/processing/Lexicon.py

https://github.com/storyscript/runtime/pull/510 except the language drops.

Revert #510

---

setup.py

Details: https://github.com/storyscript/storyscript/releases/tag/0.24.2

Upgrade Storyscript to 0.24.2

---

storyruntime/ServiceUsage.py
tests/unit/ServiceUsage.py

Closes https://github.com/storyscript/runtime/issues/565

ServiceUsage: don't scrape deleted apps

---

tests/integration/processing/Lexicon.py

Add test for bool + bool

---

storyruntime/processing/Services.py
tests/unit/processing/Services.py

Closes #336 
Closes #570 
Closes #571

Add more type checks for service call arguments

---

tests/integration/processing/Lexicon.py

See https://github.com/storyscript/runtime/issues/582

Add test for if-context assignments

---

storyruntime/processing/Lexicon.py
storyruntime/utils/Resolver.py
tests/integration/processing/Lexicon.py
tests/unit/processing/Lexicon.py

Closes https://github.com/storyscript/runtime/issues/585

Support `foreach list as index, value`

---

README.md

Improve README shields: CircleCI + CodeCov

---

storyruntime/omg/ServiceOutputValidator.py
tests/unit/omg/ServiceOutputValidator.py

Closes https://github.com/storyscript/runtime/issues/367

Check for boolean in service output validation

---

storyruntime/utils/Resolver.py

Closes https://github.com/storyscript/runtime/issues/276

Remove not_equal, greater_equal, greater

---

tests/integration/processing/Lexicon.py

Closes #524, closes #575 
Not perfect, but better
Deleted the confusing `test_mutation` and moved tests out to different suites accordingly

Refactor lexicon integration tests

---

storyruntime/processing/mutations/ListMutations.py
tests/integration/processing/Mutations.py

Add list.join mutation

---

storyruntime/Exceptions.py
tests/unit/Exceptions.py

Increase message length to 512 from 125.

---

storyruntime/App.py

App#start_services needs to iterate through every single line to find out services which it needs to start beforehand (at the time of deployment). However, with Storyscript compiler 0.25.x, next no longer indicates the actual next line, but it respects the scope. With regard to this, no services are discovered to be bootstrapped.

Iterate over all lines using the compilation tree directly.

---

storyruntime/processing/Lexicon.py
tests/unit/processing/Lexicon.py

Reverts storyscript/runtime#667

Revert "Sync up."

---

storyruntime/processing/Lexicon.py
tests/unit/processing/Lexicon.py

Reverts storyscript/runtime#668

Reapply #666

---

storyruntime/entities/Multipart.py
storyruntime/http_handlers/StoryEventHandler.py
storyruntime/processing/Services.py
tests/unit/http_handlers/StoryEventHandler.py
tests/unit/processing/Services.py
tests/unit/utils/Resolver.py

See also the OMS update: https://github.com/storyscript/http/pull/59

Expose request files under .files

---

storyruntime/processing/Lexicon.py
tests/integration/processing/Lexicon.py

Fixes https://github.com/storyscript/runtime/issues/685

Execute try blocks without a next

---

storyruntime/http_handlers/StoryEventHandler.py
tests/unit/http_handlers/StoryEventHandler.py

Follow-up to https://github.com/storyscript/runtime/pull/657.
See also: https://sentry.io/organizations/asyncy/issues/1304743754/?project=1206501&query=is%3Aunresolved

StoryEventHandler: fix content_type
